apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 8760h0m0s
  renewBefore: 72h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-proxy-injector-tls
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-tls
  duration: 8760h0m0s
  renewBefore: 72h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-smi-metrics-tls
  namespace: linkerd
spec:
  secretName: linkerd-smi-metrics-tls
  duration: 8760h0m0s
  renewBefore: 72h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-smi-metrics.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-sp-validator-tls
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-tls
  duration: 8760h0m0s
  renewBefore: 72h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-tap-tls
  namespace: linkerd
spec:
  secretName: linkerd-tap-tls
  duration: 8760h0m0s
  renewBefore: 72h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-tap.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
