apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-certificates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '25'
spec:
  destination:
    namespace: linkerd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/jon-walton/linkerd2-gitops-example.git
    targetRevision: HEAD
    path: manifests/certificates
